### ISSUE TITLE
Compatible with Electron 21+ / V8's Memory Cage?

### ISSUE THREAD

**Issue by hrueger** [Julusian/node-freetype2#3]
Hi,
is it compatible with the [Memory Cage of Electron 21+](https://www.electronjs.org/blog/v8-memory-cage)?
I just don't want to risk that it works on my machine and users of my application are doing something differently and it crashes for them ;-)

**Comment by Julusian** [comment]
Sorry, didn't have notifications turned on here for some reason...

I believe so, I can't see anywhere that could trigger that

**Comment by hrueger** [comment]
No problem, I have so many dependencies that I feel like I won't be able to update for the next 10 years ;-)
Thanks for the response 👍

**Comment by Julusian** [comment]
Well, the next patch versions of electron should all include a change which means that the memory cage issue wont cause a crash, but will result in the buffer allocation to fail. so things will still break, but it shouldnt be a fatal crash anymore
